### ISSUE TITLE
Feature request:  Configurable schemas folder name

### ISSUE THREAD

**Issue by chaeron** [yamalight/graffiti#10]
Cool project!

Any chance you could add the ability to specify the location of the mongoose schemas to the config?

You cannot assume that all projects will want to have their schemas in a folder called schemas, when graffiti is an "add on" to an existing project.

**Comment by yamalight** [comment]
That's a pretty good idea. I'd prefer to keep the folder name same, but adding `basePath` to config (similar to how Next.js does this) should solve the issue 🤔

**Comment by chaeron** [comment]
If you're gonna make it configurable, make the whole name configurable, not just the path. There is no reason to dictate the folder name. ;-)

For example, we have a healthcare application with very complex mongoose schemas....and we keep them all in a folder called models.  That is to distinguish from schemas, which are JSON schemas in our world, which are then used to code generate the actual mongoose models.

But keep the default as "schemas" in the root level.....

**Comment by yamalight** [comment]
Interesting 🤔
I guess it's relatively straightforward config thing anyways, so why not 😅

**Comment by yamalight** [comment]
Shipped in graffiti@1.1.0! 🚀
