### ISSUE TITLE
Do we have to create custom resolvers for arrays of ObjectID's in order to get subfield access in graphql?

### ISSUE THREAD

**Issue by Cigoler** [yamalight/graffiti#13]
It's an awesome project, I'm just trying it out now, and wondering whether this can't be automated or if it is what I'm missing?

As an example if you have a CAR model, that has many PARTS and you store them as an array of objectids, it looks like you have to resort to custom resolvers to get it working in a way that allows you to access those subfields?

**Comment by yamalight** [comment]
This is already implemented, see: https://github.com/yamalight/graffiti/tree/master/examples/relations

**Comment by Cigoler** [comment]
Hey thanks for responding,

So using that example I can get this kind of data structure

```
{
  "data": {
    "noteMany": [
      {
        "_id": "5ffb4fad5af85cbae8a50c0f",
        "name": "First Ever Note",
        "group": {
          "_id": "5ffb4f6d5af85cbae8a50c0d",
          "name": "Main Group"
        }
      },
      {
        "_id": "5ffb4fc15af85cbae8a50c10",
        "name": "Second Note we've created",
        "group": {
          "_id": "5ffb4f6d5af85cbae8a50c0d",
          "name": "Main Group"
        }
      },
      {
        "_id": "5ffb4fd65af85cbae8a50c11",
        "name": "Third Note with no group",
        "group": null
      },
      {
        "_id": "5ffb502a5af85cbae8a50c12",
        "name": "Fourth Note",
        "group": {
          "_id": "5ffb4f745af85cbae8a50c0e",
          "name": "Secondary Group"
        }
      }
    ]
  }
}
```

and:

```
{
  "data": {
    "collectionMany": [
      {
        "_id": "5ffb4f6d5af85cbae8a50c0d",
        "name": "Main Group"
      },
      {
        "_id": "5ffb4f745af85cbae8a50c0e",
        "name": "Secondary Group"
      }
    ]
  }
}
```

My knowledge is pretty thinly spread so apologies if this is totally obvious but I'm struggling to understand.

If I was to create a Post, and a single Post could have many Comments, in GraphQL I would expect to be able to query those Comments from within the Post query wouldn't I? So in the example above each collection has a number of notes assigned, but there's no way of accessing them directly that I can see.

Hopefully I'm making sense.

**Comment by yamalight** [comment]
@Cigoler yep, in that case you'll need to define custom resolver (see [this example](https://github.com/yamalight/graffiti/tree/master/examples/relations-manual)).
This is required because in your schema you only have one relation ("comment belongs to post"), whereas you want to run custom query ("give me all comments for current post").
If you design your relations in a way where "post has many comments" - query would work without need for any additional resolvers (but querying the other way around would likely require additional custom resolvers).

**Comment by Cigoler** [comment]
Cheers, that's the one, I figured I'd had to write some extra code but that's not too bad.
